import React from "react";
import { ArrowUpRight, Check, Home, MapPin, Package, Phone } from "lucide-react";
import { useNavigate } from "react-router-dom";
import BottomNavigation from "./components/BottomNavigation";

const readReservation = () => { try { return JSON.parse(localStorage.getItem("nearGoLastReservation") || "null"); } catch { return null; } };

export default function CustomerReservationConfirmation() {
  const navigate = useNavigate();
  const reservation = readReservation();
  return <main className="min-h-screen bg-[#f6f7f3] pb-28 text-[#173d3b]"><div className="mx-auto flex min-h-[calc(100vh-7rem)] max-w-2xl items-center px-5 py-10 sm:px-8"><section className="w-full border border-[#e3e1d9] bg-[#fffdfa] p-7 text-center shadow-[0_14px_35px_rgba(24,45,61,0.06)] sm:p-12"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#e5f1ec] text-[#3b806a]"><Check size={38} strokeWidth={2.5} /></div><p className="mt-7 text-xs font-bold uppercase tracking-[0.2em] text-[#f28a2e]">Reservation received</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">The shop has your request.</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-[#7c8583]">Keep an eye on your order status. We will show you when the shop confirms your pickup.</p>{reservation ? <div className="mt-8 border border-[#d7e5dd] bg-[#edf5f2] p-5 text-left"><div className="flex gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center bg-white"><img src={reservation.image} alt={reservation.name} className="h-full w-full object-contain p-2 mix-blend-multiply" /></div><div><h2 className="font-bold">{reservation.name}</h2><p className="mt-1 text-sm text-[#607b76]">{reservation.shop} · Qty {reservation.quantity || 1}</p><p className="mt-2 text-sm font-bold text-[#3b806a]">{reservation.pickupDate} · {reservation.pickupTime}</p></div></div><div className="mt-5 space-y-3 border-t border-[#cfe0d5] pt-4 text-sm text-[#607b76]"><p className="flex items-start gap-2"><MapPin size={16} className="mt-0.5 text-[#f28a2e]" />Pickup at {reservation.shop}</p><p className="flex items-center gap-2"><Package size={16} className="text-[#f28a2e]" />Status: <b className="text-[#b75d17]">Pending confirmation</b></p></div></div> : <div className="mt-8 border border-[#ead0c8] bg-[#fbefeb] p-4 text-sm text-[#a45d4c]">Reservation details could not be loaded. You can check Orders for the latest status.</div>}<div className="mt-8 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => navigate("/CustomerOrders")} className="flex items-center justify-center gap-2 bg-[#113b52] py-3 text-sm font-bold text-white"><Package size={16} /> View my orders</button><button type="button" onClick={() => navigate("/Nearby")} className="flex items-center justify-center gap-2 border border-[#d7dcd6] py-3 text-sm font-bold"><ArrowUpRight size={16} /> Continue shopping</button></div></section></div><BottomNavigation active="Orders" /></main>;
}
