export const customerProducts = [
  {
    id: 1,
    name: "iQOO Z9 5G",
    category: "Mobile",
    details: "8GB + 128GB · Ocean Blue",
    price: 17999,
    shopId: "sharma-mobiles",
    shop: "Sharma Mobiles",
    distance: "1.2 km",
    stock: "In stock",
    fresh: "2h ago",
    rating: "4.6",
    emoji: "📱",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=700&q=85",
  },
  {
    id: 2,
    name: "Philips LED Bulb",
    category: "Electrical",
    details: "9W · Cool Day Light",
    price: 149,
    shopId: "sharma-electricals",
    shop: "Sharma Electricals",
    distance: "0.8 km",
    stock: "In stock",
    fresh: "1h ago",
    rating: "4.8",
    emoji: "💡",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=700&q=85",
  },
  {
    id: 3,
    name: "Taparia Screwdriver Set",
    category: "Hardware",
    details: "6 pcs · Multi-purpose",
    price: 349,
    shopId: "gupta-hardware",
    shop: "Gupta Hardware",
    distance: "1.6 km",
    stock: "In stock",
    fresh: "3h ago",
    rating: "4.5",
    emoji: "🛠️",
    image: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=700&q=85",
  },
  {
    id: 4,
    name: "Classmate Notebook",
    category: "Stationery",
    details: "200 pages · Single line",
    price: 65,
    shopId: "city-book-store",
    shop: "City Book Store",
    distance: "0.6 km",
    stock: "In stock",
    fresh: "30m ago",
    rating: "4.7",
    emoji: "📓",
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=700&q=85",
  },
  {
    id: 5,
    name: "boAt Type-C Cable",
    category: "Mobile",
    details: "1.5m · Fast charging",
    price: 299,
    shopId: "gupta-mobile-store",
    shop: "Gupta Mobile Store",
    distance: "1.1 km",
    stock: "In stock",
    fresh: "2h ago",
    rating: "4.4",
    emoji: "🔌",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=700&q=85",
  },
  {
    id: 6,
    name: "Drill Bit Set",
    category: "Hardware",
    details: "10 pcs · Heavy duty",
    price: 499,
    shopId: "gupta-hardware",
    shop: "Gupta Hardware",
    distance: "1.6 km",
    stock: "In stock",
    fresh: "4h ago",
    rating: "4.5",
    emoji: "🔧",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=700&q=85",
  },
];

export const customerShops = {
  "sharma-mobiles": { id: "sharma-mobiles", name: "Sharma Mobiles", category: "Mobile & Accessories", distance: "1.2 km", rating: "4.6", phone: "+91 98765 43210", address: "56 MG Road, Indore", open: true },
  "sharma-electricals": { id: "sharma-electricals", name: "Sharma Electricals", category: "Electricals & Lighting", distance: "0.8 km", rating: "4.8", phone: "+91 98270 11223", address: "14 Siyaganj Market, Indore", open: true },
  "gupta-hardware": { id: "gupta-hardware", name: "Gupta Hardware", category: "Hardware & Tools", distance: "1.6 km", rating: "4.5", phone: "+91 98930 44321", address: "22 Jawahar Marg, Indore", open: true },
  "city-book-store": { id: "city-book-store", name: "City Book Store", category: "Stationery & Books", distance: "0.6 km", rating: "4.7", phone: "+91 97550 77881", address: "8 RNT Marg, Indore", open: false },
  "gupta-mobile-store": { id: "gupta-mobile-store", name: "Gupta Mobile Store", category: "Mobile & Accessories", distance: "1.1 km", rating: "4.4", phone: "+91 97700 33445", address: "31 Palasia Main Road, Indore", open: true },
};
